### ISSUE TITLE
Modularize the Codebase

### ISSUE THREAD

**Issue by ArindamPal-0** [ArindamPal-0/gdown-cli-golang#7]
Separate the Google Drive API and Google Auth API code in a separate module.

**Comment by arindampal-0** [comment]
- Google auth abstraction in `./internal/gdown/google-oauth-api.go`
- google drive API abstraction in `./internal/gdown/google-drive-api.go`
- CLI application (to be made) abstraction in `./internal/cli/cli.go`
- Any utility stuff in `./internal/gdown/utils.go`

All the Google API abstractions will be under the `gdown` package and CLI abstraction will be under the `cli` package.
